[build-system]
build-backend = "hatchling.build"
requires = [
  "hatch-vcs>=0.4",
  "hatchling>=1.25",
]

[project]
name = "k-butler"
dynamic = [ "version" ]
description = "K-Butler"
authors = [
    {name = "K-Tech", email = "info@k-tech.it"},
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.7",
    "pyqt6-webengine>=6.7.0",
    "pyqt6>=6.7.1",
    "pypdf2>=3.0.1",
    "pyperclip>=1.9.0",
    "platformdirs>=4.3.6",
    "pytest-qt>=4.4.0",
    "pydantic>=2.10.5",
    "email-validator>=2.2.0",
]

[project.scripts]
k-butler = "k_butler.start:main"

[dependency-groups]
dev = [
    "PyMarkdown>=0.1.4",
    "cairosvg>=2.7.1",
    "markupsafe>=2.1.5",
    "mdx-gh-links>=0.4",
    "pre-commit>=4.0.1",
    "ruff>=0.12.12",
]
docs = [
  "mkdocs>=1.5.3",
  "mkdocs-awesome-pages-plugin>=2.9.3",
  "mkdocs-click>=0.8.1",
  "mkdocs-ezglossary-plugin>=1.6.10",
  "mkdocs-ezlinks-plugin>=0.1.14",
  "mkdocs-gen-files>=0.5",
  "mkdocs-get-deps>=0.2",
  "mkdocs-include-markdown-plugin>=6.2.2",
  "mkdocs-link-marker>=0.1.3",
  "mkdocs-macros-plugin>=1.0.5",
  "mkdocs-material[imaging]>=9.5.15",
  "mkdocs-minify-plugin",
  "mkdocs-redirects",
  "mkdocs-simple-hooks>=0.1.5",
  "mkdocstrings[python]>=0.24.1",
  "pymdown-extensions>=10.7.1",
]
test = [
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
    "pytest-xdist>=3.8",
    "tox>=4.25",
]
exe_builder = [
    "pyinstaller>=6.11.0",
]

[tool.hatch]
build.hooks.vcs.version-file = "src/k_butler/version.py"
version.source = "vcs"
raw-options = { root = "../.." }

[tool.hatch.build.targets.wheel]
packages = [ "src/k_butler" ]

[tool.uv]
default-groups = [ "dev", "test", "docs", "exe_builder" ]
