import yaml
from PyQt6.QtWidgets import QWidget, QVBoxLayout, QPushButton
from pydantic_core import ValidationError

from k_butler.components.common import GuiTextEdit, GuiModal
from k_butler.strategies.base import StrategyBase


class ConfigEditor(QWidget):
    def __init__(self, strategy=None, is_global=False, *args, **kwargs):
        """
        Initializes the ConfigEditor widget.

        Args:
            strategy (StrategyBase or None): The strategy to configure.
        """
        super().__init__(*args, **kwargs)
        self.is_global = is_global
        layout = QVBoxLayout()

        self.strategy = strategy
        self.config_editor = GuiTextEdit()
        self.save_config_button = QPushButton('Save Config')
        self.save_config_button.setDefault(True)
        self.save_config_button.setToolTip('Select a strategy to configure')
        self.save_config_button.clicked.connect(self.save_config)

        if not strategy and not is_global:
            self.config_editor.setText('')
            self.config_editor.setPlaceholderText('No strategies to configure')
            self.config_editor.setReadOnly(True)
            self.save_config_button.setVisible(False)
        if is_global:
            self.strategy = StrategyBase()
        self.update_config(strategy=self.strategy)

        layout.addWidget(self.config_editor)
        layout.addWidget(self.save_config_button)
        self.setLayout(layout)

    def save_config(self) -> None:
        """
        Validate and Saves the configuration of the selected strategy or global.
        """
        config_text: str = self.config_editor.toPlainText()
        if self.strategy:
            try:
                config_data: dict = yaml.safe_load(config_text)
                self.strategy.validator.validate(config_data)
                self.strategy.configurator.write_config(config_data)
                self.update_config(strategy=self.strategy)
                GuiModal('Success', 'Configuration saved')
            except ValidationError as e:
                GuiModal('Error', f'invalid config:{str(e.errors()[0]["msg"])}')
            except Exception as e:
                GuiModal('Error', f'{e}')
        else:
            GuiModal('Error', 'No strategy selected')

    def update_config(self, *args, **kwargs):

        self.strategy = kwargs['strategy']
        if not self.strategy:
            return

        config, is_example = self.strategy.configurator.configure()
        if is_example:
            GuiModal('warning', 'There is no Config, you are using the autogenerated one')

        self.save_config_button.setVisible(True)
        self.save_config_button.setDisabled(False)
        self.save_config_button.setToolTip('Save')
        self.config_editor.setReadOnly(False)
        parse_data = yaml.dump(config, default_flow_style=False)
        self.config_editor.setText(parse_data)


class ListButton(QWidget):
    def __init__(self, items: dict[str, StrategyBase], on_strategy_selected, *args, **kwargs):
        """
        Initializes the ListButton widget.

        Args:
            items (dict): A dictionary of strategies where each key is the name of the strategy and
                the value is the strategy object itself.
            on_strategy_selected (function): A function that will be called when a strategy is selected.
        """
        super().__init__(*args, **kwargs)
        layout = QVBoxLayout()
        self.on_strategy_selected = on_strategy_selected

        for strategy_name, strategy in items.items():
            button = QPushButton(strategy_name)
            button.setDefault(False)
            button.clicked.connect(lambda _, s=strategy: self._select_strategy(s))
            layout.addWidget(button)

        self.setLayout(layout)

    def _select_strategy(self, strategy):
        for button in self.findChildren(QPushButton):
            button.setDefault(button.text() == strategy.configurator.name)
        self.on_strategy_selected(strategy=strategy)
