import yaml
from PyQt6.QtWidgets import QWidget, QVBoxLayout, QGroupBox, QGridLayout, QPushButton
from yaml._yaml import ScannerError

from k_butler.components.common import GuiTextEdit, GuiModal, GuiAccordion
from k_butler.configuration import ConfigStorage
from k_butler.strategies.base import Registry
import ast


def create_accordion_item():
    accordion_item = {}
    strategies = Registry().strategies

    for strategy in strategies:
        if strategies[strategy].configurator is not None:
            title = strategies[strategy].configurator.name
            accordion_item[title] = strategies[strategy]
    return accordion_item


class ConfigTab(QWidget):
    tabLabel = 'Config'

    def get_label(self):
        return self.tabLabel

    def __init__(self, parent=..., *args):
        super().__init__(parent, *args)
        main_layout = QVBoxLayout()
        self.editor = GuiTextEdit()
        self.editor.setReadOnly(True)
        self.editor.setPlaceholderText('Select one strategy to configure')
        self.current_strategy = None

        self.config_storage = ConfigStorage(strategy_key=self.current_strategy)

        self.save_config_button = QPushButton('Save Config')
        self.save_config_button.setDefault(True)
        self.save_config_button.setDisabled(True)
        self.save_config_button.setToolTip('Select one strategy to configure')
        self.save_config_button.clicked.connect(lambda: self.validate_dict(self.editor.toPlainText()))

        action_layout = QGroupBox('Actions')
        layout = QGridLayout()
        items = create_accordion_item()

        strategy_toolbox = GuiAccordion(items, self.update_text, is_config=True)

        layout.addWidget(strategy_toolbox, 1, 1)
        layout.addWidget(self.save_config_button, 2, 2)
        layout.addWidget(self.editor, 1, 2)

        action_layout.setLayout(layout)
        main_layout.addWidget(action_layout)
        self.setLayout(main_layout)

    def update_text(self, *args, **kwargs):

        self.save_config_button.setDisabled(False)
        self.save_config_button.setToolTip('Save')
        self.editor.setReadOnly(False)

        strategy = kwargs['strategy']
        self.current_strategy = strategy
        config, is_example = self.config_storage.read()
        if is_example:
            GuiModal('warning', 'There is no Config, you are using the autogenerated one')
        parse_data = yaml.dump(config, default_flow_style=False)
        self.editor.setText(parse_data)

    def validate_dict(self, text):
        if self.current_strategy:
            try:
                validated_yaml = yaml.safe_load(text)
                self.config_storage.write(validated_yaml)
                self.update_text(strategy=self.current_strategy)
            except Exception as e:
                GuiModal('error', str(e))
        else:
            GuiModal('warning', 'Select one strategy to configure')
