from PyQt6.QtWidgets import QWidget, QVBoxLayout, QGroupBox, QGridLayout, QPushButton

from k_butler.components.common import GuiTextEdit, GuiModal, GuiAccordion
from k_butler.configuration import ConfigStorage
from k_butler.strategies.base import Registry
import ast


def create_accordion_item():
    accordion_item = {}
    strategies = Registry().strategies

    for strategy in strategies:
        if strategies[strategy].configurator is not None:
            title = strategies[strategy].configurator.name
            accordion_item[title] = strategies[strategy]
    return accordion_item


class ConfigTab(QWidget):
    tabLabel = 'Config'

    def get_label(self):
        return self.tabLabel

    def __init__(self, parent=..., *args):
        super().__init__(parent, *args)
        main_layout = QVBoxLayout()
        self.editor = GuiTextEdit()
        self.current_strategy = None

        self.config_storage = ConfigStorage(strategy_key=self.current_strategy)

        save_config_button = QPushButton('Save Config')
        save_config_button.setDefault(True)
        save_config_button.clicked.connect(lambda: self.validate_dict(self.editor.toPlainText()))

        action_layout = QGroupBox('Actions')
        layout = QGridLayout()
        items = create_accordion_item()

        strategy_toolbox = GuiAccordion(items, self.update_text, is_config=True)

        layout.addWidget(strategy_toolbox, 1, 1)
        layout.addWidget(save_config_button, 2, 2)
        layout.addWidget(self.editor, 1, 2)

        action_layout.setLayout(layout)
        main_layout.addWidget(action_layout)
        self.setLayout(main_layout)

    def update_text(self, *args, **kwargs):
        strategy = kwargs['strategy']
        self.current_strategy = strategy
        config, is_example = self.config_storage.read()
        if is_example:
            GuiModal('warning', 'There is no Config, you are using the autogenerated one')
        self.editor.setText(str(config))

    def validate_dict(self, text):
        try:
            res = ast.literal_eval(text)
            self.config_storage.write(res)
            updated_text, _ = self.config_storage.read()
            self.editor.setText(str(updated_text))

        except Exception:
            GuiModal('error', 'Config not valid')
